### ISSUE TITLE
License page down, unable to activate purchase

### ISSUE THREAD

**Issue by gorfreed** [stranoweb/stranoweb-ajax-login#13]
Upon having to reinstall the plugin (which always requires manual removal, download, upload and activation of the plugin for each update), the activation key got deleted. I am unable to retrieve it though since your license page is 404 (https://www.ajaxlogin.com/my-account/view-license-keys/). The problems with this plugin just don't end. I understand if you want to secure your premium content but if you cannot support it technically, then you shouldn't try safety copy protection that is simply not applied to Wordpress by any of your competition. It's a shame because I still think that Stranoweb is really the most beautiful floating login screen.

**Comment by stranoweb** [comment]
Hi Gorfreed, I'm sorry to hear that.
Let me help you, will answer to your points:

1) Regarding the updates, you don't need to deactivate the plugin and reactivate on each update. We always write the steps to follow in our newsletter, simply overwrite the old files with the new ones via FTP (no need to deativate first) or if you don't have FTP access, download and install the plugin "Easy Theme and Plugin Upgrades" which anyway I recommend you to install because is very useful, and upload our plugin in the regular way from plugin page, as a new plugin.

2) You are right, my apologise, the license page was offline due an update we did of license manager plugin, now it's fixed.

Hope this may be of help and thanks for your understanding.
