### ISSUE TITLE
Browser back button problem

### ISSUE THREAD

**Issue by delorimier** [stranoweb/stranoweb-ajax-login#22]
When logged in with Stranoweb, if I leave for another site and use back button, admin bar no longer showing, logout link becomes login. But I am still logged in, refreshing page will revert to correct display. If I deactivate the plugin, problem disappears (need to log in again normally).

Great plugin by the way, nicely done.

**Comment by delorimier** [comment]
Checking 'Disable SWAL nonce' fixes the problem. Hoping to be able to activate this security feature in the future. Thank you.

**Comment by stranoweb** [comment]
Hi Delorimier, thanks for using our plugin.

That maybe a browser caching issue, but if disabling nonces solves the problem that's good.
We thought about that feature to add some extra security to the forms, but we are thinking to a set it as disabled by default. That's just a little bit of extra security, but not the biggets one for sure.
For example, if you are using a caching plugin you need to disable that option, otherwise nonce verification fails most of the time. Default WP login and register forms don't have nonce verification.

If you have any other question don't hesitate to ask.

**Comment by delorimier** [comment]
Hi, 
Thanks for the info. There is no caching on this current project. Setting nonce to off by default sounds like a good idea. Looking forward to using this plugin on future projects. Thanks again.
